// <auto-generated />
using System;
using ApiRestControlFlota.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRestControlFlota.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230615235919_PrimeraMigracion")]
    partial class PrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiRestControlFlota.Models.Vehiculo", b =>
                {
                    b.Property<int>("VEI_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VEI_Id"));

                    b.Property<string>("VEI_CodigoVehiculo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("VEI_Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VEI_FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VEI_Habilitado")
                        .HasMaxLength(250)
                        .HasColumnType("bit");

                    b.Property<int>("VEI_KmInicial")
                        .HasColumnType("int");

                    b.Property<string>("VEI_Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VEI_PesoLimite")
                        .HasColumnType("int");

                    b.Property<string>("VEI_PlacaVehiculo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("VEI_TimeStand")
                        .HasColumnType("datetime2");

                    b.HasKey("VEI_Id");

                    b.ToTable("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
