// <auto-generated />
using System;
using ApiRestControlFlota.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRestControlFlota.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230616170052_change_Column_VIA_Destino")]
    partial class change_Column_VIA_Destino
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiRestControlFlota.Models.Conductor", b =>
                {
                    b.Property<int>("CON_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CON_Id"));

                    b.Property<string>("CON_ApellidosConductor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CON_CedulaConductor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CON_FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CON_FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CON_Habilitado")
                        .HasColumnType("bit");

                    b.Property<string>("CON_NombresConductor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("CON_TimeStand")
                        .HasColumnType("datetime2");

                    b.Property<string>("CON_TipoLicencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CON_Id");

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("ApiRestControlFlota.Models.GastoPorVehiculo", b =>
                {
                    b.Property<int>("GPV_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GPV_Id"));

                    b.Property<string>("GPV_Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GPV_FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GPV_Habilitado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GPV_TimeStand")
                        .HasColumnType("datetime2");

                    b.Property<double>("GPV_Valor")
                        .HasColumnType("float");

                    b.Property<string>("VEI_CodigoVehiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GPV_Id");

                    b.ToTable("GastoPorVehiculos");
                });

            modelBuilder.Entity("ApiRestControlFlota.Models.Vehiculo", b =>
                {
                    b.Property<int>("VEI_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VEI_Id"));

                    b.Property<string>("VEI_CodigoVehiculo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("VEI_Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VEI_FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VEI_Habilitado")
                        .HasColumnType("bit");

                    b.Property<int?>("VEI_KmInicial")
                        .HasColumnType("int");

                    b.Property<string>("VEI_Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VEI_PesoLimite")
                        .HasColumnType("int");

                    b.Property<string>("VEI_PlacaVehiculo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("VEI_TimeStand")
                        .HasColumnType("datetime2");

                    b.HasKey("VEI_Id");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("ApiRestControlFlota.Models.Viajes", b =>
                {
                    b.Property<int>("VIA_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VIA_Id"));

                    b.Property<int>("CON_CedulaConductor")
                        .HasColumnType("int");

                    b.Property<string>("VEI_CodigoVehiculo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("VIA_Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIA_DetallesViaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIA_Empresa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("VIA_FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("VIA_Habilitado")
                        .HasColumnType("bit");

                    b.Property<int>("VIA_KmRecorridos")
                        .HasColumnType("int");

                    b.Property<string>("VIA_Manifiesto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("VIA_Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("VIA_PagoCombustible")
                        .HasColumnType("float");

                    b.Property<double?>("VIA_PagoConductor")
                        .HasColumnType("float");

                    b.Property<double?>("VIA_PagoOtros")
                        .HasColumnType("float");

                    b.Property<double?>("VIA_PagoPeajes")
                        .HasColumnType("float");

                    b.Property<DateTime?>("VIA_TimeStand")
                        .HasColumnType("datetime2");

                    b.Property<double?>("VIA_Utilidades")
                        .HasColumnType("float");

                    b.Property<double?>("VIA_ValorViaje")
                        .HasColumnType("float");

                    b.HasKey("VIA_Id");

                    b.ToTable("Viajes");
                });
#pragma warning restore 612, 618
        }
    }
}
